Vagrant.configure("2") do |config|

	config.vm.box = "bento/ubuntu-18.04"
	
	config.vm.provision "shell", path: "bootstrap.sh"
    
	# Kubernetes Master Server
	config.vm.define "kmaster" do |kmaster|
		kmaster.vm.hostname = "kmaster.formation.com"
		kmaster.vm.network "private_network", ip: "192.168.33.100"
		kmaster.vm.provider "virtualbox" do |v|
			v.name = "kmaster"
			v.memory = 6048
			v.cpus = 2
		end
		kmaster.vm.provision "shell", path: "bootstrap_kmaster.sh"
	end


    config.vm.define "kworker1" do |workernode|
		workernode.vm.hostname = "kworker1.formation.com"
		workernode.vm.network "private_network", ip: "192.168.33.10"
		workernode.vm.provider "virtualbox" do |v|
			v.name = "kworker1"
			v.memory = 6048
			v.cpus = 2
		end
		workernode.vm.provision "shell", path: "bootstrap_kworker.sh"
    end
    
end