postgresql_python_library: python3-psycopg2

postgresql_global_config_options:
  - option: listen_addresses
    value: '*'

postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: peer }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, ip_mask: 0.0.0.0/0, auth_method: md5 }
  - { type: local, database: delivery, user: delivery, auth_method: md5 }

postgresql_databases:
  - name: delivery 

postgresql_users:
  - name: delivery #required; the rest are optional
    password: delivery
    db: delivery
