apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service-${BRANCH_NAME}
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      name: delivery-service-${BRANCH_NAME}
  template:
    metadata:
      labels:
        name: delivery-service-${BRANCH_NAME}
    spec:
      containers:
      - name: delivery-service-${BRANCH_NAME}
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: prod,swagger
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config-${BRANCH_NAME}
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config-${BRANCH_NAME}
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config-${BRANCH_NAME}
                key: POSTGRES_DB
          - name: POSTGRES_SERVICE
            valueFrom:
              configMapKeyRef:
                name: postgres-config-${BRANCH_NAME}
                key: POSTGRES_SERVICE
        image: ${IMAGE}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 5        
      imagePullSecrets:
        - name: regcred


